# Generated by Django 2.0.7 on 2018-07-14 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=15)),
                ('lat_pos', models.FloatField()),
                ('lon_pos', models.FloatField()),
                ('station_pic', models.ImageField(default='default/defaultstation.png', upload_to='station_img/')),
            ],
        ),
        migrations.CreateModel(
            name='SurveillanceReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('avg_capacity_index', models.FloatField()),
                ('avg_count_index', models.FloatField()),
                ('json_data', models.FileField(upload_to='')),
                ('bike_count_list', models.CharField(max_length=5)),
                ('car_count_list', models.CharField(max_length=5)),
                ('taxi_count_list', models.CharField(max_length=5)),
                ('pickup_count_list', models.CharField(max_length=5)),
                ('micro_count_list', models.CharField(max_length=5)),
                ('bus_count_list', models.CharField(max_length=5)),
                ('truck_count_list', models.CharField(max_length=5)),
                ('tempo_count_list', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SurveillanceVideo',
            fields=[
                ('surveillance_id', models.AutoField(primary_key=True, serialize=False)),
                ('surveillancevideo_name', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField()),
                ('report', models.BooleanField(default=False)),
                ('lane_dimen1', models.FloatField()),
                ('lane_dimen2', models.FloatField()),
                ('lane_dimen3', models.FloatField()),
                ('lane_dimen4', models.FloatField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveillanceapp.Station')),
            ],
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='surveillanceapp.SurveillanceVideo'),
        ),
    ]
