# Generated by Django 2.0.7 on 2018-07-27 06:25

from django.db import migrations, models
import surveillanceapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillanceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveillancevideo',
            old_name='surveillance_id',
            new_name='video_id',
        ),
        migrations.RemoveField(
            model_name='surveillancereport',
            name='bike_count_list',
        ),
        migrations.RemoveField(
            model_name='surveillancereport',
            name='bus_count_list',
        ),
        migrations.RemoveField(
            model_name='surveillancereport',
            name='car_count_list',
        ),
        migrations.RemoveField(
            model_name='surveillancereport',
            name='json_data',
        ),
        migrations.RemoveField(
            model_name='surveillancereport',
            name='micro_count_list',
        ),
        migrations.RemoveField(
            model_name='surveillancereport',
            name='pickup_count_list',
        ),
        migrations.RemoveField(
            model_name='surveillancereport',
            name='taxi_count_list',
        ),
        migrations.RemoveField(
            model_name='surveillancereport',
            name='tempo_count_list',
        ),
        migrations.RemoveField(
            model_name='surveillancereport',
            name='truck_count_list',
        ),
        migrations.RemoveField(
            model_name='surveillancevideo',
            name='lane_dimen1',
        ),
        migrations.RemoveField(
            model_name='surveillancevideo',
            name='lane_dimen2',
        ),
        migrations.RemoveField(
            model_name='surveillancevideo',
            name='lane_dimen3',
        ),
        migrations.RemoveField(
            model_name='surveillancevideo',
            name='lane_dimen4',
        ),
        migrations.RemoveField(
            model_name='surveillancevideo',
            name='surveillancevideo_name',
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='congestion_data',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='contribution_data',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='count_data',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='surveillancevideo',
            name='lane_dimens',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='surveillancevideo',
            name='video_file',
            field=models.FileField(max_length=250, null=True, upload_to=surveillanceapp.models.SurveillanceVideo.file_path),
        ),
    ]

    atomic = False
