# Generated by Django 2.0.7 on 2018-07-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillanceapp', '0002_auto_20180727_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(max_length=50),
        ),
    ]
