# Generated by Django 2.0.7 on 2018-07-27 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveillanceapp', '0003_auto_20180727_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveillancereport',
            name='congestion_data',
        ),
        migrations.RemoveField(
            model_name='surveillancereport',
            name='contribution_data',
        ),
        migrations.RemoveField(
            model_name='surveillancereport',
            name='count_data',
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='congestion_jsonfile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='contribution_jsonfile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='count_jsonfile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='report_file',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='surveillancereport',
            name='avg_capacity_index',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='surveillancereport',
            name='avg_count_index',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='surveillancevideo',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveillance_videos', to='surveillanceapp.Station'),
        ),
    ]
