# Generated by Django 2.0.7 on 2018-07-27 14:24

from django.db import migrations, models
import surveillanceapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillanceapp', '0004_auto_20180727_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveillancevideo',
            name='video_file',
            field=models.FileField(null=True),
        ),
    ]
