# Generated by Django 2.0.7 on 2018-07-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillanceapp', '0005_auto_20180727_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveillancevideo',
            name='lane_dimens',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
