# Generated by Django 2.0.7 on 2018-07-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillanceapp', '0006_auto_20180727_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveillancevideo',
            name='video_file',
        ),
        migrations.AddField(
            model_name='surveillancevideo',
            name='video_filename',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='surveillancevideo',
            name='video_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
