# Generated by Django 2.0.7 on 2018-07-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillanceapp', '0007_auto_20180727_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveillancevideo',
            name='thumbnail_filename',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
