# Generated by Django 2.0.7 on 2018-07-28 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveillanceapp', '0009_surveillancevideo_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveillancereport',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='surveillance_report', to='surveillanceapp.SurveillanceVideo'),
        ),
    ]
