# Generated by Django 2.0.7 on 2018-07-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillanceapp', '0010_auto_20180728_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveillancevideo',
            name='analysed_duration',
            field=models.BigIntegerField(default=0),
        ),
    ]
