# Generated by Django 2.0.7 on 2018-07-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillanceapp', '0011_surveillancevideo_analysed_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveillancevideo',
            name='analysed_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
