# Generated by Django 2.0.7 on 2018-07-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillanceapp', '0012_surveillancevideo_analysed_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveillancereport',
            name='passed_bike_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='passed_bus_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='passed_car_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='passed_micro_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='passed_taxi_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='passed_tempo_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='passed_truck_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='passed_vehicle_count',
            field=models.IntegerField(default=0),
        ),
    ]
