# Generated by Django 2.0.7 on 2018-07-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillanceapp', '0013_auto_20180730_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveillancereport',
            name='passed_pickup_count',
            field=models.IntegerField(default=0),
        ),
    ]
