# Generated by Django 2.0.7 on 2018-07-31 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveillanceapp', '0014_surveillancereport_passed_pickup_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveillancereport',
            old_name='avg_capacity_index',
            new_name='avg_congestion_index',
        ),
        migrations.RenameField(
            model_name='surveillancereport',
            old_name='passed_bike_count',
            new_name='outgoing_bike_count',
        ),
        migrations.RenameField(
            model_name='surveillancereport',
            old_name='passed_bus_count',
            new_name='outgoing_bus_count',
        ),
        migrations.RenameField(
            model_name='surveillancereport',
            old_name='passed_car_count',
            new_name='outgoing_car_count',
        ),
        migrations.RenameField(
            model_name='surveillancereport',
            old_name='passed_micro_count',
            new_name='outgoing_micro_count',
        ),
        migrations.RenameField(
            model_name='surveillancereport',
            old_name='passed_pickup_count',
            new_name='outgoing_pickup_count',
        ),
        migrations.RenameField(
            model_name='surveillancereport',
            old_name='passed_taxi_count',
            new_name='outgoing_taxi_count',
        ),
        migrations.RenameField(
            model_name='surveillancereport',
            old_name='passed_tempo_count',
            new_name='outgoing_tempo_count',
        ),
        migrations.RenameField(
            model_name='surveillancereport',
            old_name='passed_truck_count',
            new_name='outgoing_truck_count',
        ),
        migrations.RenameField(
            model_name='surveillancereport',
            old_name='passed_vehicle_count',
            new_name='outgoing_vehicle_count',
        ),
    ]
